### ISSUE TITLE
Additional mods

### ISSUE THREAD

**Issue by egut** [Allexio/Cinnamon#1]
Hi and thanks for  awesome modpack. 

I have a few suggestions for additional mods, I have tested these on my instance and to what I can see it renders with about the same FPS.

These two come more or less a package. Gives more video config options: 
- Sodium Extra¹ 
- Reese's Sodium Options¹ 

Game play feature: 
- Chunk loaders¹   (Simple remote chunk loaders to encourage more trains :D )

Nice addons:
- Chunks fade in¹  (fade or animate in new chuncks) 
- ModMenu Badges Lib¹  (missing, recommended by Spawn Animations)
- Here be no Dragons!¹  (Some mods are marked as experimental, lets ignore that)

Better visual experience, adds a lot of different mobs: 
- Better Animations Collection¹ 
- Wildlife¹ 
- Naturalist¹ 
- Living Things¹ 

These three might be interesting to add: 
- Animal Feeding Trough (small feature to let animals feed them self)
- Yung's - set (Yung have reworked many of the default structures to be more interesting )
- Let's Do - set (Adds add quite a few food and declarative set of things.)

These currently don't work for me, but I would love to have ships and airplanes too:
- Valkyrien Skies
- Eureka!

¹ ) Tested and seams to work fine for me.

**Comment by Allexio** [comment]
Hi @egut and thanks for your interest in my modpack 😄

Here's my point of view on the mods you would like me to add to the modpack

## Will be added:
- Sodium Extra
- Reese's Sodium Options
- Chunks fade in
  - Just the fade in though, the animation is too immersion breaking for me

## Considering:
- Naturalist
  - Ngl, some of these additions look really nice, I just want to make sure none of them make the experience of players frustrating.
- Better Animations Collection
  - I'm kinda torn on this one. Some of the animations it adds are very questionable, so if I do add it I'd have to configure it out of the box. Extra work, but I might add it.
- Chunk loaders
  - As a modpack owner this makes sense. As a server owner, I have to be _very_ careful about letting people use chunk loaders. I'll check the available config and see how much it lets me limit chunk loading per-player.
- Let's Do
  - I might add some of these (wine, perhaps?), but I will not be adding all of them, as we already have a fair chunk of new food recipes via farmer's delight. I do not think the modpack needs too much more.

## Will not be added:
- Wildlife
  - It seems like it isn't as in depth as Naturalist, so if I'll take one of the two I'd rather it be Naturalist.
- Valkyrien Skies / Eureka
  - Waaaaaaaay too unstable/bugged to be added to the modpack for now... I think this mod still needs a significant amount of time in the oven before I can even consider adding it.
- Animal Feeding Trough
  - You can do this with Create, so I will not be adding it
- Yung's
  - Had I seen this before, I might have added it to the modpack, but as it is, I have already made my choice in terms of structures revamp. If I add too many structure mods, they will end up conflicting with each other (and already do, to be honest)

Thanks again for leaving an issue and I hope you enjoy using the modpack.
I _will_ be adding some extra content to the modpack soon, so look forward to it 😄
(If CEI releases I might even be able to go 1.0 stable!)

**Comment by egut** [comment]
@Allexio  Thanks, 
I mostly aggregate with what you say :) 

- For all animal mobs its to make the world more immersive any way it do not need to be all. 
  The small birds in wildlife are very cute too, but one is better than none!
- Valkyrien Skies / Eureka - yes its not ready I agree, but please have it on your lookout list and there might come other similar, idk. 
- Chunkloader - there are config for max loaded chunk per player, but I don't know how to set it, but you might do. https://github.com/SuperMartijn642/ChunkLoaders/blob/8fc54a750bebd56ec54b6fb1532b40cf04564113/src/main/java/com/supermartijn642/chunkloaders/ChunkLoadersConfig.java#L27 

After a walk I realized that I forgot to suggest two more mods that seams fairly correct for this pack:
- Create Jetpack
- Traveler's Backpack
Both are very good for exploring the world and with the improved world generation, new/improved structures and (possible) some extra wild life and shaders the views are stunning :) 

I'm looking forward to your release. While you fix that I will look into how I want to configure my server. Thanks for pointing to itzg, I have used a similar setup a few years back but that is out of touch today :)

**Comment by egut** [comment]
@Allexio skip keeping an eye on Valkyrien Skies, if I read correct Create Simulated should work for Fabric and hopefully be released next year, as they almost could have this year, but push the release time forward. I think it will be a drop in working so we can start with your work and just continue with flights later on. :) 

- https://createsimulated.com/blog1.html
- https://www.youtube.com/@createaeronautics1997
- https://www.youtube.com/watch?v=zThmb9AAW2Y

**Comment by Allexio** [comment]
Version 1.0 now available on github.
